#!/bin/bash
discovery () {
disk=($(ls /dev/sd*|awk -F"/" '{print $3}'|grep -v '[0-9]'))
	printf '{\n'
	printf '\t"data":[\n'
for((i=0;i<${#disk[@]};++i))
{
	num=$(echo $((${#disk[@]}-1)))
	if [ "$i" != ${num} ];
		then
        printf "\t\t{ \n"
        printf "\t\t\t\"{#DISKNAME}\":\"${disk[$i]}\"},\n"
		else
			printf  "\t\t{ \n"
			printf  "\t\t\t\"{#DISKNAME}\":\"${disk[$num]}\"}]}\n"
	fi
}
}


http_disk () {
PORT=$(curl -o /dev/null -s -w %{http_code} http://60.191.140.200:$1/)
[ $PORT == 200 ] && echo ${PORT}
[ $PORT != 200 ] && echo ${PORT}
}

case "$1" in
disk)
http_disk $2
;;
discovery)
discovery
;;
test)
echo test
;;
esac
