#!/bin/bash

# function:monitor game status from zabbix
# License: GPL
# mail:itnihao@163.com
# date:2012-12-10
# status code 1 is running,status code 0 is not running


#Login，Master，Game logic，Gateway，Date log，Catabase，F拉屎

GAME=$(echo $2)
Login () {
PORT=$(/bin/netstat -nlput|awk -F":" '/Login/ {print $0}'|grep ":$1" |awk -F: '{print $2}'|awk '{print $1}')
#awk -F":" '/17660/,/Login/ {print $0}'
#PORT=$(echo `/bin/netstat -nlput|awk -F"[:]" '/ssh/ {print $4}'|grep -v "^$"`)
 if [ "$PORT" != "$GAME" ] 
     then 
       echo 0
 elif
    [ "$PORT" == "$GAME" ] 
    then
       echo 1
     
 else
       echo 2
fi
}

Master () {
PORT=$(/bin/netstat -nlput|awk -F":" '/Master/ {print $0}'|grep ":$1"|awk -F: '{print $2}'|awk '{print $1}')
 if [ "$PORT" != "$GAME" ]
     then
       echo 0
 elif
    [ "$PORT" == "$GAME" ]
    then 
       echo 1
 else
       echo 2
fi
}

Gateway () {
PORT=$(/bin/netstat -nlput|awk -F":" '/Gateway/ {print $0}'|grep ":$1"|awk -F: '{print $2}'|awk '{print $1}')
 if [ "$PORT" != "$GAME" ]
     then
       echo 0
 elif
    [ "$PORT" == "$GAME" ] 
    then
       echo 1
 else
       echo 2
fi
}

GameLogic () {
PORT=$(/bin/netstat -nlput|awk -F":" '/GameLogic/ {print $0}'|grep ":$1"|awk -F: '{print $2}'|awk '{print $1}')
 if [ "$PORT" != "$GAME" ]
     then
       echo 0
 elif
    [ "$PORT" == "$GAME" ] 
 then
    echo 1
 else
       echo 2
fi
}

Database () {
PORT=$(/bin/netstat -nlput|awk -F":" '/Database/ {print $0}'|grep ":$1"|awk -F: '{print $2}'|awk '{print $1}')
 if [ "$PORT" != "$GAME" ]
     then
       echo 0
 elif
    [ "$PORT" == "$GAME" ]
 then
      echo 1
 else
       echo 2
fi
}
Datalog () {
PORT=$(/bin/netstat -nlput|awk -F":" '/Datalog/ {print $0}'|grep ":$1"|awk -F: '{print $2}'|awk '{print $1}')
 if [ "$PORT" != "$GAME" ]
     then
       echo 0
 elif
    [ "$PORT" == "$GAME" ]
 then
      echo 1
 else
       echo 2
fi
}
Recharges () {
PORT=$(/bin/netstat -nlput|awk -F":" '/Recharges/ {print $0}'|grep ":$1"|awk -F: '{print $2}'|awk '{print $1}')
 if [ "$PORT" != "$GAME" ]
     then
       echo 0
 elif
    [ "$PORT" == "$GAME" ]
 then
      echo 1
 else
       echo 2
fi
}

FlashPolicyServer () {
PORT=$(/bin/netstat -nlput|awk -F":" '/FlashPolicy/ {print $0}'|grep ":$1"|awk -F: '{print $2}'|awk '{print $1}')
 if [ "$PORT" != "$GAME" ]
     then
       echo 0
 elif
    [ "$PORT" == "$GAME" ]
 then
      echo 1
 else
       echo 2
fi
}

ssh () {
PORT=$(/bin/netstat -nlput|awk -F":" '/ssh/ {print $0}'|grep ":$1"|awk -F: '{print $2}'|awk '{print $1}'|grep -v "^$")
 if [ "$PORT" != "$GAME" ]
     then
       echo 0
 elif
    [ "$PORT" == "$GAME" ]
 then
      echo 1
 else
       echo 2
fi
}


case "$1" in
login)
Login $2
;;
master)
Master $2
;; 
gateway)
Gateway $2
;;
gamelogic)
GameLogic $2
;;
database)
Database $2
;;
datalog)
Datalog $2
;;
recharges)
Recharges $2
;;
flashpolicyserver)
FlashPolicyServer $2
;;
*)
echo "Usage: $0  {login {port}|master {port}|gateway {port}|gamelogic {port}|database {port}|datalog {port}|recharges {port}|flashpolicyserver {port}}"
;;
esac
